monolog:
    handlers:
        # En développement, on garde les logs 10 jours
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 10  # Garde les logs des 10 derniers jours
            channels: ['!event']
        
        # Console pour voir les logs en temps réel
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
